version: "3.9"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=2jdiLek$2l;p
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./postgres-data:/var/lib/postgresql/data/pgdata

  slurk:
    build:
      context: ./slurk
      dockerfile: Dockerfile
    # image: slurk/server

    restart: on-failure
    ports:
      - 5000:80
    environment:
      - SLURK_DATABASE_URI=postgresql://postgres:2jdiLek$2l;p@db:5432/postgres
      - SLURK_SECRET_KEY=pprandslurkkey